import { createHash } from 'node:crypto';
import type { Prisma, PrismaClient } from '@prisma/client';
import { SCORING_VERSION } from '../config/constants.js';
import { computeScore, levelToApi, type CiStatus } from '../scoring/rules.js';
import { runFingerprint, stableStringify } from '../analysis/fingerprint.js';
import type { AiOutput } from '../ai/types.js';

/**
 * Deterministic, repeatable demo data (the single seed path for the DB).
 *
 *  - Demo repositories use reserved negative github_repo_id values and
 *    is_demo=true, so they can never collide with real GitHub identities.
 *  - SHAs and timestamps are derived from the scenario, never random.
 *  - Scores come from the real scoring engine and are keyed by the same run
 *    fingerprint the worker uses, so re-running creates no duplicate history.
 *  - The two AI analyses are labelled fixtures (model "demo-fixture"), not
 *    output from a model.
 */

interface Scenario {
  title: string;
  author: string;
  state: 'open' | 'closed';
  merged?: boolean;
  additions: number;
  deletions: number;
  changed_files: number;
  files: string[];
  base_ref: string;
  head_ref: string;
  ci: CiStatus;
  ci_reason?: string;
  aiFixture?: AiOutput;
}

const DEMO_REPOS = [
  { github_repo_id: -1001n, owner: 'demo-acme', name: 'webapp' },
  { github_repo_id: -1002n, owner: 'demo-acme', name: 'api' },
  { github_repo_id: -1003n, owner: 'demo-acme', name: 'infrastructure' },
] as const;

const many = (prefix: string, n: number) => Array.from({ length: n }, (_, i) => `${prefix}${i}.ts`);

export const DEMO_SCENARIOS: Scenario[] = [
  {
    title: 'Add unit tests for user service',
    author: 'alice-dev',
    state: 'open',
    additions: 120,
    deletions: 5,
    changed_files: 3,
    files: ['src/services/user.test.ts', 'src/services/user.ts', 'src/utils/helpers.test.ts'],
    base_ref: 'main',
    head_ref: 'feature/add-user-tests',
    ci: 'success',
  },
  {
    title: 'Fix typo in README',
    author: 'bob-contributor',
    state: 'closed',
    merged: true,
    additions: 2,
    deletions: 2,
    changed_files: 1,
    files: ['README.md'],
    base_ref: 'main',
    head_ref: 'fix/readme-typo',
    ci: 'success',
  },
  {
    title: 'Update dependencies',
    author: 'charlie-maintainer',
    state: 'open',
    additions: 15,
    deletions: 10,
    changed_files: 2,
    files: ['package.json', 'pnpm-lock.yaml'],
    base_ref: 'main',
    head_ref: 'chore/update-deps',
    ci: 'pending',
    ci_reason: 'checks still running',
  },
  {
    title: 'Add loading spinner component',
    author: 'diana-frontend',
    state: 'closed',
    merged: true,
    additions: 85,
    deletions: 0,
    changed_files: 2,
    files: ['src/components/LoadingSpinner.tsx', 'src/components/LoadingSpinner.test.tsx'],
    base_ref: 'main',
    head_ref: 'feature/loading-spinner',
    ci: 'success',
  },
  {
    title: 'Refactor authentication middleware',
    author: 'eve-backend',
    state: 'open',
    additions: 250,
    deletions: 180,
    changed_files: 5,
    files: ['src/middleware/auth.ts', 'src/middleware/auth.test.ts', 'src/utils/jwt.ts', 'src/config/auth.ts', 'src/types/auth.ts'],
    base_ref: 'main',
    head_ref: 'refactor/auth-middleware',
    ci: 'success',
    aiFixture: {
      summary: 'Demo fixture: the middleware refactor changes how JWTs are validated and where auth configuration is read.',
      review_focus: [
        'Token validation in src/utils/jwt.ts (expiry and signature checks)',
        'Configuration defaults in src/config/auth.ts',
        'Error paths in src/middleware/auth.ts for missing or malformed tokens',
      ],
      test_suggestions: [
        'An expired token is rejected with 401',
        'A token signed with the wrong key is rejected',
        'Requests without a token reach public routes only',
      ],
      rollback_risk: 'MED',
      confidence: 0.6,
      warnings: ['Demo fixture: not generated by an AI model'],
    },
  },
  {
    title: 'Add payment processing endpoint',
    author: 'frank-api',
    state: 'open',
    additions: 320,
    deletions: 50,
    changed_files: 5,
    files: ['src/routes/payments.ts', 'src/services/payment.ts', 'src/services/payment.test.ts', 'src/types/payment.ts', 'src/utils/validation.ts'],
    base_ref: 'main',
    head_ref: 'feature/payment-endpoint',
    ci: 'failure',
  },
  {
    title: 'Update CI/CD configuration',
    author: 'grace-devops',
    state: 'open',
    additions: 180,
    deletions: 120,
    changed_files: 4,
    files: ['.github/workflows/ci.yml', '.github/workflows/deploy.yml', 'Dockerfile', 'docker-compose.yml'],
    base_ref: 'main',
    head_ref: 'chore/update-ci',
    ci: 'success',
  },
  {
    title: 'Migrate database schema',
    author: 'henry-db',
    state: 'open',
    additions: 400,
    deletions: 200,
    changed_files: 4,
    files: ['prisma/migrations/20240115_add_users/migration.sql', 'prisma/schema.prisma', 'src/lib/db.ts', 'src/models/user.ts'],
    base_ref: 'main',
    head_ref: 'feature/db-migration',
    ci: 'unknown',
    ci_reason: 'no CI checks reported for this commit',
  },
  {
    title: 'Add feature flags system',
    author: 'ivy-platform',
    state: 'closed',
    merged: true,
    additions: 280,
    deletions: 30,
    changed_files: 4,
    files: ['src/services/feature-flags.ts', 'src/services/feature-flags.test.ts', 'src/config/flags.ts', 'src/middleware/flags.ts'],
    base_ref: 'main',
    head_ref: 'feature/feature-flags',
    ci: 'success',
  },
  {
    title: 'Major refactor: Rewrite authentication system',
    author: 'jack-senior',
    state: 'open',
    additions: 1200,
    deletions: 800,
    changed_files: 45,
    files: ['src/auth/login.ts', 'src/auth/session.ts', 'src/auth/middleware.ts', 'src/auth/utils.ts', 'src/auth/types.ts', 'src/services/user.ts', 'src/config/auth.ts', ...many('src/auth/file', 38)],
    base_ref: 'main',
    head_ref: 'refactor/auth-system',
    ci: 'success',
    aiFixture: {
      summary: 'Demo fixture: a 45-file rewrite of login and session handling with no test changes.',
      review_focus: [
        'Session creation and invalidation in src/auth/session.ts',
        'Login flow in src/auth/login.ts, including failure handling',
        'Auth configuration changes in src/config/auth.ts',
        'Consider splitting the change into smaller reviewable PRs',
      ],
      test_suggestions: [
        'Login with valid and invalid credentials',
        'Session expiry and logout revoke access',
        'Concurrent sessions for one user behave as intended',
        'Regression tests for every endpoint behind the auth middleware',
      ],
      rollback_risk: 'HIGH',
      confidence: 0.55,
      warnings: ['Demo fixture: not generated by an AI model'],
    },
  },
  {
    title: 'Implement payment gateway integration',
    author: 'karen-payments',
    state: 'open',
    additions: 1500,
    deletions: 200,
    changed_files: 55,
    files: ['src/payments/stripe.ts', 'src/payments/paypal.ts', 'src/payments/billing.ts', 'src/payments/invoice.ts', 'src/services/payment.ts', 'src/config/payments.ts', ...many('src/payments/module', 49)],
    base_ref: 'main',
    head_ref: 'feature/payment-gateway',
    ci: 'pending',
    ci_reason: 'checks still running',
  },
];

const BASE_TIME = Date.UTC(2026, 0, 5, 9, 0, 0);
const DAY = 24 * 3600_000;

function demoSha(title: string): string {
  return createHash('sha1').update(`demo:${title}`).digest('hex');
}

/** Split PR churn across files deterministically (for per-file fingerprints). */
function fileChurn(s: Scenario) {
  const n = s.files.length;
  return s.files.map((filename, i) => ({
    filename,
    status: 'modified',
    additions: Math.floor(s.additions / n) + (i < s.additions % n ? 1 : 0),
    deletions: Math.floor(s.deletions / n) + (i < s.deletions % n ? 1 : 0),
  }));
}

export async function seedDemoData(prisma: PrismaClient): Promise<{ repositories: number; pull_requests: number; new_scores: number }> {
  const repos = [];
  for (const r of DEMO_REPOS) {
    const data = {
      full_name: `${r.owner}/${r.name}`,
      owner: r.owner,
      name: r.name,
      installation_id: 0n,
      private: false,
      visibility: 'public',
      is_demo: true,
      access_status: 'active',
      access_revoked_at: null,
    };
    repos.push(await prisma.repo.upsert({ where: { github_repo_id: r.github_repo_id }, update: data, create: { github_repo_id: r.github_repo_id, ...data } }));
  }

  let newScores = 0;
  for (const [i, s] of DEMO_SCENARIOS.entries()) {
    const repo = repos[i % repos.length];
    const number = i + 1;
    const headSha = demoSha(s.title);
    const createdAt = new Date(BASE_TIME + i * DAY);
    const updatedAt = new Date(BASE_TIME + i * DAY + 6 * 3600_000);
    const closedAt = s.state === 'closed' ? new Date(BASE_TIME + i * DAY + 8 * 3600_000) : null;
    const prData = {
      title: s.title,
      state: s.state,
      draft: false,
      author: s.author,
      head_sha: headSha,
      base_ref: s.base_ref,
      head_ref: s.head_ref,
      additions: s.additions,
      deletions: s.deletions,
      changed_files: s.changed_files,
      changed_files_list: s.files,
      identity_status: 'verified',
      github_created_at: createdAt,
      github_updated_at: updatedAt,
      closed_at: closedAt,
      merged_at: s.merged ? closedAt : null,
    };
    const pr = await prisma.pullRequest.upsert({
      where: { repo_id_number: { repo_id: repo.id, number } },
      update: prData,
      create: { repo_id: repo.id, number, ...prData },
    });

    const files = fileChurn(s);
    const coverage = { expected_files: s.changed_files, listed_files: s.files.length, complete: s.files.length >= s.changed_files };
    const scoring = computeScore({
      changed_files: s.changed_files,
      additions: s.additions,
      deletions: s.deletions,
      changed_files_list: s.files,
      ci_status: s.ci,
      ci_reason: s.ci_reason,
      coverage,
    });
    const fingerprint = runFingerprint({
      scoringVersion: SCORING_VERSION,
      headSha,
      baseRef: s.base_ref,
      changedFiles: s.changed_files,
      additions: s.additions,
      deletions: s.deletions,
      files,
      fileListComplete: coverage.complete,
      ciStatus: s.ci,
    });

    const existing = await prisma.analysisRun.findUnique({
      where: { pull_request_id_input_fingerprint: { pull_request_id: pr.id, input_fingerprint: fingerprint } },
    });
    if (existing) continue;

    const json = (v: unknown) => JSON.parse(stableStringify(v)) as Prisma.InputJsonValue;
    await prisma.$transaction(async (tx) => {
      const run = await tx.analysisRun.create({
        data: {
          pull_request_id: pr.id,
          head_sha: headSha,
          input_fingerprint: fingerprint,
          scoring_version: SCORING_VERSION,
          ci_status: s.ci,
          ai_status: s.aiFixture ? 'succeeded' : 'disabled',
          comment_status: 'disabled',
          completed_at: updatedAt,
          created_at: updatedAt,
        },
      });
      await tx.prScore.create({
        data: {
          pull_request_id: pr.id,
          run_id: run.id,
          score: scoring.score,
          level: levelToApi(scoring.level),
          reasons: scoring.reasons,
          features: json(scoring.features),
          contributions: json(scoring.contributions),
          coverage: json({ ...coverage, files_without_patch: 0, reason: coverage.complete ? null : 'demo file list is abbreviated', uncertainties: scoring.uncertainties }),
          head_sha: headSha,
          scoring_version: SCORING_VERSION,
          ci_status: s.ci,
          input_fingerprint: fingerprint,
          created_at: updatedAt,
        },
      });
      if (s.aiFixture) {
        await tx.prAiAnalysis.create({
          data: {
            pull_request_id: pr.id,
            run_id: run.id,
            analysis_json: json(s.aiFixture),
            model: 'demo-fixture',
            prompt_version: 'demo',
            head_sha: headSha,
            input_fingerprint: `demo:${fingerprint}`,
            limitations: json({ note: 'Static demo fixture; no model was called.' }),
            created_at: updatedAt,
          },
        });
      }
    });
    newScores += 1;
  }

  return { repositories: repos.length, pull_requests: DEMO_SCENARIOS.length, new_scores: newScores };
}
