import type { Octokit } from '@octokit/rest';
import { COMMENT_MARKER } from '../config/constants.js';
import type { AiLimitations, AiOutput } from '../ai/types.js';
import { PermanentError } from '../lib/errors.js';
import { withGitHubRetry } from './retry.js';

export interface CommentContext {
  headSha: string;
  score: number;
  level: 'low' | 'medium' | 'high';
  ciStatus: string;
  uncertainties: string[];
  analysis: AiOutput;
  limitations: AiLimitations | null;
  model: string;
}

/** Stop AI text from pinging users/teams or injecting the marker/HTML comments. */
function neutralizeText(text: string): string {
  return text
    .replace(/<!--|-->/g, '')
    .replace(/@(?=[A-Za-z0-9-])/g, '@​')
    .replace(/[\r\n]+/g, ' ')
    .trim();
}

export function formatAnalysisComment(ctx: CommentContext): string {
  const a = ctx.analysis;
  const list = (items: string[]) => items.slice(0, 5).map((i) => `- ${neutralizeText(i)}`).join('\n');
  const notes: string[] = [...ctx.uncertainties];
  if (ctx.limitations) {
    const l = ctx.limitations;
    if (l.truncated_files.length) notes.push(`Diffs truncated for: ${l.truncated_files.join(', ')}`);
    if (l.omitted_files.length) notes.push(`Diffs omitted (budget) for: ${l.omitted_files.join(', ')}`);
    if (l.missing_patch_files.length) notes.push(`No diff available (binary/too large): ${l.missing_patch_files.join(', ')}`);
  }
  for (const w of a.warnings ?? []) notes.push(`Model warning: ${w}`);

  return [
    COMMENT_MARKER,
    '## PR Risk Scorer',
    '',
    `**Risk score:** ${ctx.score}/100 (${ctx.level}) · **CI:** ${ctx.ciStatus} · **Analyzed revision:** \`${ctx.headSha.slice(0, 12)}\``,
    '',
    `**AI summary:** ${neutralizeText(a.summary)}`,
    '',
    '### Review focus',
    list(a.review_focus),
    '',
    '### Suggested tests',
    list(a.test_suggestions),
    '',
    `**Rollback risk (model estimate):** ${a.rollback_risk} · **Model-reported confidence:** ${Math.round(a.confidence * 100)}%`,
    ...(notes.length ? ['', '<details><summary>Limitations</summary>', '', list(notes), '', '</details>'] : []),
    '',
    `<sub>Advisory only. Generated by ${neutralizeText(ctx.model)} from the risk score and up to three diffs; it can be wrong. ` +
      'The score is a review-prioritisation heuristic, not proof of correctness. This comment is updated in place for new revisions.</sub>',
  ].join('\n');
}

interface IssueComment {
  id: number;
  body?: string;
  performed_via_github_app?: { id?: number } | null;
}

function isOurs(comment: IssueComment, appId: number): boolean {
  return comment.performed_via_github_app?.id === appId && (comment.body ?? '').includes(COMMENT_MARKER);
}

/**
 * Find this app's analysis comment. Verifies authorship (created via this
 * GitHub App and carrying the marker) so a user's comment is never edited,
 * and paginates so the comment is found on long threads — including one whose
 * id was never saved because the process crashed right after creating it.
 */
export async function findOwnComment(
  gh: Octokit,
  params: { owner: string; repo: string; number: number; appId: number; storedCommentId: bigint | null },
): Promise<number | null> {
  const { owner, repo, number, appId, storedCommentId } = params;
  if (storedCommentId !== null) {
    try {
      const { data } = await withGitHubRetry('issues.getComment', () =>
        gh.rest.issues.getComment({ owner, repo, comment_id: Number(storedCommentId) }),
      );
      if (isOurs(data as IssueComment, appId)) return data.id;
    } catch (err) {
      // Deleted comment → fall through to reconciliation.
      if (!(err instanceof PermanentError && err.kind === 'github_not_found')) throw err;
    }
  }
  const comments = await withGitHubRetry('issues.listComments', () =>
    gh.paginate(gh.rest.issues.listComments, { owner, repo, issue_number: number, per_page: 100 }),
  );
  const ours = (comments as IssueComment[]).filter((c) => isOurs(c, appId));
  return ours.length ? ours[ours.length - 1].id : null;
}

/** Create or update the single analysis comment; returns its id. */
export async function upsertAnalysisComment(
  gh: Octokit,
  params: { owner: string; repo: string; number: number; appId: number; storedCommentId: bigint | null; body: string },
): Promise<{ commentId: number; created: boolean }> {
  const existing = await findOwnComment(gh, params);
  const { owner, repo, number, body } = params;
  if (existing !== null) {
    await withGitHubRetry('issues.updateComment', () => gh.rest.issues.updateComment({ owner, repo, comment_id: existing, body }));
    return { commentId: existing, created: false };
  }
  // POST is not idempotent: a retried create after a 5xx could duplicate the
  // comment. Create exactly once; a failure is retried by a later run, which
  // reconciles (finds an already-created comment by marker) before creating.
  const { data } = await withGitHubRetry(
    'issues.createComment',
    () => gh.rest.issues.createComment({ owner, repo, issue_number: number, body }),
    { maxAttempts: 1 },
  );
  return { commentId: data.id, created: true };
}
